### PR TITLE
Upgrade webpack to 2.2

### LINKED ISSUE #22: Not working with Webpack 2 beta
My tests that were working with Webpack 1 and rewire now fail under webpack 2 beta.

I receive the error: 

```
C:\Users\sudsy\Development\gen3\PVL.Content\tests\node_modules\webpack\node_modules\enhanced-resolve\lib\Resolver.js:86
        if(callback.stack) {
                   ^

TypeError: Cannot read property 'stack' of undefined
    at Tapable.doResolve (C:\Users\sudsy\Development\gen3\PVL.Content\tests\node_modules\webpack\node_modules\enhanced-resolve\lib\Resolver.js:86:13)
    at Tapable.next (C:\Users\sudsy\Development\gen3\PVL.Content\tests\node_modules\enhanced-resolve\lib\ModuleAliasPlugin.js:37:19)
    at Tapable.<anonymous> (C:\Users\sudsy\Development\gen3\PVL.Content\tests\node_modules\enhanced-resolve\lib\ModuleAliasPlugin.js:42:5)
```

### PR DESCRIPTION
**Pull request by RSO**
This PR is pretty much the result of me banging my head against the wall while trying to get the tests running. All tests are supposed to show up green now!

Seeing how this plugin seems to be pretty much set in terms of what it does, I figured a major release would be the way to go., unless someone can figure out a pretty way to support both versions of webpack next to each other.

Should fix #22

### CODE REVIEW

**Comment by rtibbles** [comment]
This saved my build - gets my vote!

**Comment by RSO** [comment]
NOTE: I just discovered a strange problem in our own testsuite on Webpack2.2. It seems that second/third runs don't properly rewire resources. I have no clue what is going on, and we decided to actually move away from rewire, so I won't be able to update this PR. I hope that somebody else will be able to figure out what's going on!

**Comment by nadavsinai** [comment]
@RSO thanks for your work, I'm curious what are you using instead of rewire?

**Comment by RSO** [comment]
Not using anything anymore, we've decided that unit-tests like this add less value to our codebase in comparison to the pain they add. In some cases we found other ways around rewire, for instance in cases where we had to mock `window.location =`, we decide to create a `redirectHelper` that actually returns a `sinon.spy()` when called in the test environment.

In other cases we decided that mocking was just simply not the way to go.

**Pull request closed without merging**
